# Generated by Django 4.2.7 on 2024-12-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
